# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Character.create(name: "Tielfang", lvl: 3)
Character.create(name: "Chitter", lvl: 5)

# Races
Race.create(name: "Human")
Race.create(name: "Dragonborn")
Race.create(name: "Elf")
Race.create(name: "Gnome")
Race.create(name: "Dwarf")
Race.create(name: "Half-Elf")
Race.create(name: "Half-Orc")
Race.create(name: "Halfling")
Race.create(name: "Tiefling")
Race.create(name: "Aarakocra")
Race.create(name: "Aasimar")
Race.create(name: "Firbolg")
Race.create(name: "Genasi")
Race.create(name: "Gith")
Race.create(name: "Goliath")
Race.create(name: "Kenku")
Race.create(name: "Locathah")
Race.create(name: "Tabaxi")
Race.create(name: "Tortle")
Race.create(name: "Triton")
Race.create(name: "Bugbear")
Race.create(name: "Centaur")
Race.create(name: "Goblin")
Race.create(name: "Grung")
Race.create(name: "Hobgoblin")
Race.create(name: "Kobold")
Race.create(name: "Lizardfolk")
Race.create(name: "Minotaur")
Race.create(name: "Orc")
Race.create(name: "Yuan-Ti")

# Classes
Classs.create(name: "Barbarian")
Classs.create(name: "Artificer")
Classs.create(name: "Bard")
Classs.create(name: "Blood Hunter")
Classs.create(name: "Cleric")
Classs.create(name: "Druid")
Classs.create(name: "Fighter")
Classs.create(name: "Monk")
Classs.create(name: "Paladin")
Classs.create(name: "Ranger")
Classs.create(name: "Rogue")
Classs.create(name: "Sorcerer")
Classs.create(name: "Warlock")
Classs.create(name: "Wizard")
